### PR TITLE
Add "after" option to ListOrders.

### PR DESCRIPTION
**Pull request by raphael**
Add ability to unregister from streams.
Fix bug with page size option in GetAccountActivities.

### CODE REVIEW

**Comment by sam3000** [comment]
The Unsubscribe method is nice but should be in a separate PR.
The ListOrders change breaks the API.  I think it'll need something like ListOrdersAfter() instead.

**Comment by shlomikushchi** [comment]
Hi @raphael 
Thanks a lot for the contribution.
as @sam3000 mentioned, you are adding a lot of code in one PR, which makes it difficult to do this merge.
The common way is to create a separate PR for each subject. Easier to review and merge.
There are good things in here there I want to merge, so if you could split this PR to small PRs we could do the iteration of merging. if not, I will manually copy pieces of code so what ever is convenient for you is fine. thanks.

**Comment by shlomikushchi** [comment]
Also, do note that unsubscribe exists already in this PR: https://github.com/alpacahq/alpaca-trade-api-go/pull/98
so there's no need for that code in a separate PR.

**Comment by raphael** [comment]
That makes sense, sorry for the rushed PR. I'll see if I get time to refactor - closing this for now.

**Pull request closed without merging**
